version: '3.9'

services:
  payment-service:
    build: .
    container_name: payment-service
    ports:
      - "5005:4000"
      - "9229:9229"
    environment:
      PORT: 4000
      DB_HOST: shared-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: main
      KAFKA_BROKER: kafka:9092
    networks:
      - shared-infra
    entrypoint: [ "/bin/sh", "-c", "sleep 10 && node --inspect=0.0.0.0:9229 src/app.js" ]

networks:
  shared-infra:
    external: true
